kind: Deployment
apiVersion: apps/v1
metadata:
  name: foofoo
  labels:
    app: foofoo
spec:
  replicas: 2
  selector:
    matchLabels:
      app: foofoo
  template:
    metadata:
      labels:
        app: foofoo
    spec:
      containers:
        - name: foofoo
          image: enigmaxz/frontend
          imagePullPolicy: Always
          ports:
            - containerPort: 5000
      restartPolicy: Always
---
kind: Service
apiVersion: v1
metadata:
  name: foofoo
spec:
  type: NodePort
  ports:
    - port: 5000
      targetPort: 5000
      protocol: TCP
      nodePort: 31000
  selector:
    app: foofoo
