kind: Service
apiVersion: v1
metadata:
  name: rabbitmq
  namespace: idiot-or-not
spec:
  type: NodePort
  ports:
    - port: 15672
      targetPort: 15672
      protocol: TCP
      nodePort: 31123
  selector:
    app: rabbitmq
