kind: Deployment
apiVersion: apps/v1
metadata:
  name: foofoo
  namespace: idiot-or-not
  labels:
    app: foofoo
spec:
  replicas: 2
  selector:
    matchLabels:
      app: foofoo
  template:
    metadata:
      labels:
        app: foofoo
    spec:
      containers:
        - name: foofoo
          image: alxegore/foofoo
          imagePullPolicy: Always
          ports:
            - containerPort: 5000
      restartPolicy: Always
