apiVersion: apps/v1
kind: Deployment
metadata:
  name: leaderboard
  namespace: idiot-or-not
spec:
  replicas: 1
  selector:
    matchLabels:
      app: leaderboard
  template:
    metadata:
      labels:
        app: leaderboard
    spec:
      containers:
        - name: leaderboard
          image: enigmaxz/leaderboard
          imagePullPolicy: Always
          ports:
            - containerPort: 80
      dnsConfig:
        options:
        - name: ndots
          value: "2"
