apiVersion: apps/v1
kind: Deployment
metadata:
    name: leaderboard
    namespace: idiot-or-not
spec:
    replicas: 2
    selector:
        matchLabels:
            app: leaderboard
    template:
        metadata:
            labels:
                app: leaderboard
        spec:
            containers:
                - name: leaderboard
                  image: patipong1998/idiot-or-not-leaderboard
                  imagePullPolicy: Always
                  ports:
                      - containerPort: 80
