apiVersion: v1
kind: Service
metadata:
  name: api-gateway-service
  namespace: idiot-or-not
spec:
  selector:
    app: api-gateway
  ports:
    - protocol: TCP
      port: 8090
      targetPort: 8090
      nodePort: 31113
