apiVersion: v1
kind: Service
metadata:
  name: api-gateway
  namespace: idiot-or-not
spec:
  type: NodePort
  selector:
    app: api-gateway
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 31115
