kind: Service
apiVersion: v1
metadata:
  name: check-ans
  namespace: idiot-or-not

spec:
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
  selector:
    app: check-ans


# kubectl apply -f check-ans.yaml (deployment)
# kubectl apply -f check-ans.yaml (service)
# minikube service check-ans --url 

# kubectl get deployments
# kubectl get services
# kubectl get pods

