apiVersion: v1
kind: Service
metadata:
    name: leaderboard
    namespace: idiot-or-not
spec:
    selector:
        app: leaderboard
    ports:
        - protocol: TCP
          port: 80
          targetPort: 80
