apiVersion: v1
kind: Service
    name: leaderboard
    namespace: idiot-or-not
spec:
    type: NodePort
    selector:
        app: leaderboard
    ports:
        - protocol: TCP
          port: 80
          targetPort: 80
          nodePort: 30001
