apiVersion: v1
kind: Service
metadata:
    name: leaderboard
spec:
    type: NodePort
    selector:
        app: leaderboard
    ports:
        - protocol: TCP
          port: 80
          targetPort: 80
          nodePort: 30001
